include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart,./**.yaml]
linter:
  rules:
    public_member_api_docs: false
    use_build_context_synchronously: false