name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  verify-dart:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main

  verify-flutter:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@main

  build:
    needs: [verify-dart, verify-flutter]

    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'
