name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
#   verify-dart:
#     uses: Gonzaa25/compras_app/.github/workflows/dart_package.yml@master

  verify-flutter:
    uses: Gonzaa25/compras_app/.github/workflows/my_flutter_package.yml@master

  build:
    needs: [verify-flutter]
#     needs: [verify-dart, verify-flutter]

    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'
